/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uaspd2;

/**
 *
 * @author asus
 */
public class MENUUTAMA extends javax.swing.JFrame {

    /**
     * Creates new form MENUUTAMA
     */
    public MENUUTAMA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxnasigoreng = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtjumlah1 = new javax.swing.JTextField();
        cbxnasigorengspesial = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtjumlah2 = new javax.swing.JTextField();
        cbxsotospesial = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtjumlah3 = new javax.swing.JTextField();
        cbxtahulontong = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtjumlah4 = new javax.swing.JTextField();
        cbxtehmanis = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        txtjumlah5 = new javax.swing.JTextField();
        cbxesjeruk = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        txtjumlah6 = new javax.swing.JTextField();
        cbxpopice = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        txtjumlah7 = new javax.swing.JTextField();
        cbxnutrisari = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        txtjumlah8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txapesan1 = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cbxkentanggoreng = new javax.swing.JRadioButton();
        cbxcireng = new javax.swing.JRadioButton();
        cbxsosis = new javax.swing.JRadioButton();
        cbxkebab = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtjumlah9 = new javax.swing.JTextField();
        txtjumlah10 = new javax.swing.JTextField();
        txtjumlah11 = new javax.swing.JTextField();
        txtjumlah12 = new javax.swing.JTextField();

        jRadioButton4.setText("Soto Spesial");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Rp.12.000,-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DAFTAR MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(349, 11, 212, 33);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 166, 0, 0);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(808, 295, 0, 24);

        jLabel9.setText("Menu Makanan :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(26, 60, 79, 14);

        jLabel10.setText("Harga :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(165, 60, 36, 14);

        jLabel11.setText("Jumlah :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(285, 60, 40, 14);

        jLabel12.setText("Menu Minuman :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(548, 60, 78, 14);

        jLabel13.setText("Harga :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(667, 60, 36, 14);

        jLabel14.setText("Jumlah :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(762, 60, 40, 14);

        cbxnasigoreng.setText("Nasi Goreng");
        cbxnasigoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnasigorengActionPerformed(evt);
            }
        });
        getContentPane().add(cbxnasigoreng);
        cbxnasigoreng.setBounds(26, 85, 83, 23);

        jLabel3.setText("Rp.10.000,-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(165, 89, 59, 14);

        txtjumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtjumlah1);
        txtjumlah1.setBounds(277, 86, 56, 20);

        cbxnasigorengspesial.setText("Nasi Goreng Spesial");
        cbxnasigorengspesial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnasigorengspesialActionPerformed(evt);
            }
        });
        getContentPane().add(cbxnasigorengspesial);
        cbxnasigorengspesial.setBounds(26, 111, 119, 23);

        jLabel4.setText("Rp.14.000,-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(163, 115, 59, 14);
        getContentPane().add(txtjumlah2);
        txtjumlah2.setBounds(277, 112, 56, 20);

        cbxsotospesial.setText("Soto Spesial");
        cbxsotospesial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsotospesialActionPerformed(evt);
            }
        });
        getContentPane().add(cbxsotospesial);
        cbxsotospesial.setBounds(26, 138, 83, 23);

        jLabel5.setText("Rp.12.000,-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(163, 144, 59, 14);
        getContentPane().add(txtjumlah3);
        txtjumlah3.setBounds(277, 138, 56, 20);

        cbxtahulontong.setText("Tahu Lontong");
        cbxtahulontong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtahulontongActionPerformed(evt);
            }
        });
        getContentPane().add(cbxtahulontong);
        cbxtahulontong.setBounds(26, 163, 91, 23);

        jLabel8.setText("Rp.9000,-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(163, 163, 49, 23);
        getContentPane().add(txtjumlah4);
        txtjumlah4.setBounds(277, 164, 56, 20);

        cbxtehmanis.setText("Teh Manis");
        getContentPane().add(cbxtehmanis);
        cbxtehmanis.setBounds(533, 87, 73, 23);

        jLabel15.setText("Rp.3.000,-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(667, 91, 53, 14);
        getContentPane().add(txtjumlah5);
        txtjumlah5.setBounds(762, 88, 56, 20);

        cbxesjeruk.setText("Es jeruk");
        getContentPane().add(cbxesjeruk);
        cbxesjeruk.setBounds(533, 113, 63, 23);

        jLabel16.setText("Rp.4.000,-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(664, 117, 53, 14);

        txtjumlah6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtjumlah6);
        txtjumlah6.setBounds(762, 114, 56, 20);

        cbxpopice.setText("Pop Ice");
        getContentPane().add(cbxpopice);
        cbxpopice.setBounds(533, 139, 61, 23);

        jLabel17.setText("Rp.7.000,-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(664, 143, 53, 14);
        getContentPane().add(txtjumlah7);
        txtjumlah7.setBounds(762, 140, 56, 20);

        cbxnutrisari.setText("Nutrisari");
        getContentPane().add(cbxnutrisari);
        cbxnutrisari.setBounds(533, 166, 65, 23);

        jLabel18.setText("Rp.10.000,-");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(479, 85, 59, 0);
        getContentPane().add(txtjumlah8);
        txtjumlah8.setBounds(762, 167, 56, 20);

        jLabel19.setText("Rp.5000,-");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(664, 170, 49, 14);

        jLabel20.setText("Daftar Pesannan :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(12, 229, 88, 14);

        txapesan1.setColumns(20);
        txapesan1.setRows(5);
        jScrollPane1.setViewportView(txapesan1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(104, 214, 424, 236);

        btnpesan.setText("PESAN");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });
        getContentPane().add(btnpesan);
        btnpesan.setBounds(583, 368, 225, 23);

        jButton1.setText("NOMER ANTRIAN ");
        getContentPane().add(jButton1);
        jButton1.setBounds(583, 402, 225, 23);

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(583, 337, 225, 23);

        jLabel21.setText("Snack");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(548, 195, 41, 14);

        cbxkentanggoreng.setText("Kentang Goreng");
        cbxkentanggoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkentanggorengActionPerformed(evt);
            }
        });
        getContentPane().add(cbxkentanggoreng);
        cbxkentanggoreng.setBounds(533, 214, 103, 23);

        cbxcireng.setText("Cireng");
        getContentPane().add(cbxcireng);
        cbxcireng.setBounds(533, 240, 57, 23);

        cbxsosis.setText("Sosis");
        cbxsosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsosisActionPerformed(evt);
            }
        });
        getContentPane().add(cbxsosis);
        cbxsosis.setBounds(533, 266, 49, 23);

        cbxkebab.setText("Kebab");
        cbxkebab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkebabActionPerformed(evt);
            }
        });
        getContentPane().add(cbxkebab);
        cbxkebab.setBounds(533, 292, 55, 23);

        jLabel22.setText("Rp.12.000,-");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(664, 218, 59, 14);

        jLabel23.setText("Rp.10.000,-");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(664, 244, 59, 14);

        jLabel24.setText("Rp.10.000,-");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(664, 270, 59, 14);

        jLabel25.setText("Rp.15.000,-");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(664, 296, 59, 14);
        getContentPane().add(txtjumlah9);
        txtjumlah9.setBounds(762, 215, 56, 20);
        getContentPane().add(txtjumlah10);
        txtjumlah10.setBounds(762, 241, 56, 20);
        getContentPane().add(txtjumlah11);
        txtjumlah11.setBounds(762, 267, 56, 20);
        getContentPane().add(txtjumlah12);
        txtjumlah12.setBounds(762, 293, 56, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxnasigorengspesialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnasigorengspesialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxnasigorengspesialActionPerformed

    private void cbxsotospesialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsotospesialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxsotospesialActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void cbxtahulontongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtahulontongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxtahulontongActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int bayar = 0;
        if(cbxnasigoreng.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah1.getText());
            int total;
            total=jumlah*10000;
            bayar=bayar+total;
            tampil +=cbxnasigoreng.getText()+ "Rp.10.000,-" +jumlah+" = "+total+"\n";
        } if(cbxnasigorengspesial.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah2.getText());
            int total;
            total=jumlah*14000;
            bayar=bayar+total;
            tampil +=cbxnasigorengspesial.getText()+ "Rp.14.000,-" +jumlah+" = "+total+"\n";
        } if(cbxsotospesial.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah3.getText());
            int total;
            total=jumlah*12000;
            bayar=bayar+total;
            tampil +=cbxsotospesial.getText()+ "Rp.12.000,-" +jumlah+" = "+total+"\n";
        }if(cbxtahulontong.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah4.getText());
            int total;
            total=jumlah*9000;
            bayar=bayar+total;
            tampil +=cbxtahulontong.getText()+ "Rp.9.000,-" +jumlah+" = "+total+"\n";
        }if(cbxtehmanis.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah5.getText());
            int total;
            total=jumlah*3000;
            bayar=bayar+total;
            tampil +=cbxtehmanis.getText()+ "Rp.3.000,-" +jumlah+" = "+total+"\n";
        }if(cbxesjeruk.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah6.getText());
            int total;
            total=jumlah*4000;
            bayar=bayar+total;
            tampil +=cbxesjeruk.getText()+ "Rp.4.000,-" +jumlah+" = "+total+"\n";
        }if(cbxpopice.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah7.getText());
            int total;
            total=jumlah*7000;
            bayar=bayar+total;
            tampil +=cbxpopice.getText()+ "Rp.7.000,-" +jumlah+" = "+total+"\n";
        }if(cbxnutrisari.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah8.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil +=cbxnutrisari.getText()+ "Rp.12.000,-" +jumlah+" = "+total+"\n";
        }if(cbxkentanggoreng.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah9.getText());
            int total;
            total=jumlah*12000;
            bayar=bayar+total;
            tampil +=cbxkentanggoreng.getText()+ "Rp.10.000,-" +jumlah+" = "+total+"\n";
        }if(cbxcireng.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah10.getText());
            int total;
            total=jumlah*10000;
            bayar=bayar+total;
            tampil +=cbxcireng.getText()+ "Rp.10.000,-" +jumlah+" = "+total+"\n";
        }if(cbxsosis.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah11.getText());
            int total;
            total=jumlah*10000;
            bayar=bayar+total;
            tampil +=cbxsosis.getText()+ "Rp.10.000,-" +jumlah+" = "+total+"\n";
        }if(cbxkebab.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah12.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil +=cbxkebab.getText()+ "Rp.15.000,-" +jumlah+" = "+total+"\n";
        }
        txapesan1.setText(tampil+"======================================================"+"\n"+"Total Bayar ="+bayar);
      
         
   
   
           
    }//GEN-LAST:event_btnpesanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtjumlah1.setText("");
        txtjumlah2.setText("");
        txtjumlah3.setText("");
        txtjumlah4.setText("");
        txtjumlah5.setText("");
        txtjumlah6.setText("");
        txtjumlah7.setText("");
        txtjumlah8.setText("");
        txtjumlah9.setText("");
        txtjumlah10.setText(""); 
        txtjumlah11.setText("");
        txtjumlah12.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxnasigorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnasigorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxnasigorengActionPerformed

    private void txtjumlah6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah6ActionPerformed

    private void txtjumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah1ActionPerformed

    private void cbxkentanggorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxkentanggorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxkentanggorengActionPerformed

    private void cbxsosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxsosisActionPerformed

    private void cbxkebabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxkebabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxkebabActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENUUTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENUUTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENUUTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENUUTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENUUTAMA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpesan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton cbxcireng;
    private javax.swing.JRadioButton cbxesjeruk;
    private javax.swing.JRadioButton cbxkebab;
    private javax.swing.JRadioButton cbxkentanggoreng;
    private javax.swing.JRadioButton cbxnasigoreng;
    private javax.swing.JRadioButton cbxnasigorengspesial;
    private javax.swing.JRadioButton cbxnutrisari;
    private javax.swing.JRadioButton cbxpopice;
    private javax.swing.JRadioButton cbxsosis;
    private javax.swing.JRadioButton cbxsotospesial;
    private javax.swing.JRadioButton cbxtahulontong;
    private javax.swing.JRadioButton cbxtehmanis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea txapesan1;
    private javax.swing.JTextField txtjumlah1;
    private javax.swing.JTextField txtjumlah10;
    private javax.swing.JTextField txtjumlah11;
    private javax.swing.JTextField txtjumlah12;
    private javax.swing.JTextField txtjumlah2;
    private javax.swing.JTextField txtjumlah3;
    private javax.swing.JTextField txtjumlah4;
    private javax.swing.JTextField txtjumlah5;
    private javax.swing.JTextField txtjumlah6;
    private javax.swing.JTextField txtjumlah7;
    private javax.swing.JTextField txtjumlah8;
    private javax.swing.JTextField txtjumlah9;
    // End of variables declaration//GEN-END:variables
}
